services:

  mongo:
   image: mongo
   container_name: mongo
   volumes:
    - mongo_data:/data/db
   networks:
    - ms-network

  patient-service:
    build:
      context: ./patient-service
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - ms-network
    environment:
      - INTERNAL_AUTH_TOKEN=5cd9b5e6-fe30-4b2d-a0c0-0095e03fa8c5
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=patient_db

  note-service:
    build:
      context: ./note-service
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    networks:
      - ms-network
    environment:
      - INTERNAL_AUTH_TOKEN=5cd9b5e6-fe30-4b2d-a0c0-0095e03fa8c5
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=note_db

  diabetes-assessment-service:
    build:
      context: ./diabetes-assessment-service
    ports:
      - "8083:8083"
    depends_on:
      - patient-service
      - note-service
    networks:
      - ms-network
    environment:
      - INTERNAL_AUTH_TOKEN=5cd9b5e6-fe30-4b2d-a0c0-0095e03fa8c5

  gateway-service:
    build:
      context: ./gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - patient-service
      - note-service
      - diabetes-assessment-service
    networks:
      - ms-network
    environment:
      - INTERNAL_AUTH_TOKEN=5cd9b5e6-fe30-4b2d-a0c0-0095e03fa8c5
      - USER=user
      - PASSWORD=userpass

  frontend:
    build:
      context: ./medialabo-front
    ports:
      - "3000:3000"
    depends_on:
      - gateway-service
    networks:
      - ms-network

networks:
  ms-network:

volumes:
  mongo_data:
